./gameboy BROKER CAUGHT_POKEMON 2 OK
./gameboy BROKER CAUGHT_POKEMON 3 OK
./gameboy BROKER CAUGHT_POKEMON 4 OK
./gameboy BROKER CAUGHT_POKEMON 5 20
./gameboy BROKER CAUGHT_POKEMON 6 OK
./gameboy BROKER CAUGHT_POKEMON 7 OK